# Generated by Django 5.0.1 on 2025-03-12 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_solde"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("country_code", models.CharField(max_length=5, unique=True)),
                ("allowed_prefixes", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.country",
            ),
        ),
    ]
