# Generated by Django 5.0.1 on 2025-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(default="MR", max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
