# Generated by Django 5.0.1 on 2025-06-15 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_created_at_customuser_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="country",
        ),
    ]
