# Generated by Django 5.0.1 on 2025-06-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="solde",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
