# Generated by Django 5.0.1 on 2025-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="status",
            field=models.CharField(
                choices=[("Open", "open"), ("Closed", "closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
