# Generated by Django 5.0.1 on 2025-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0002_alter_fund_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="current_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="fund",
            name="total_participants",
            field=models.IntegerField(default=0),
        ),
    ]
