# Generated by Django 5.0.1 on 2025-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funds", "0003_alter_fund_current_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fund",
            old_name="onwer",
            new_name="owner",
        ),
    ]
