# Generated by Django 5.0.1 on 2025-06-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funds", "0004_rename_onwer_fund_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="current_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="fund",
            name="target_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
